import LeanPhy.Mathematics.Hilbert
import LeanPhy.Mathematics.LinearFlow
import LeanPhy.Quantum.Unitary
import Mathlib.Tactic

/-!
# Finite matrices into the basis-free Hilbert API

This file is deliberately an adapter rather than a second operator theory.
`Matrix.toEuclideanLin` supplies the canonical finite-dimensional Hilbert
space `EuclideanSpace 𝕜 ι`; the theorems below transport matrix multiplication,
conjugate transpose, self-adjointness and unitarity into the common bounded
operator interface.  The finite-dimensional hypothesis stays visible in the
type of the construction, so no claim about unbounded or infinite-dimensional
operators is introduced.
-/

namespace LeanPhy.Mathematics.Hilbert

open scoped ComplexConjugate

noncomputable def euclideanMatrixOperator {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (A : Matrix ι ι 𝕜) :
    EuclideanSpace 𝕜 ι →L[𝕜] EuclideanSpace 𝕜 ι :=
  (Matrix.toEuclideanLin A).toContinuousLinearMap

@[simp] theorem euclideanMatrixOperator_toLin {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (A : Matrix ι ι 𝕜) :
    (euclideanMatrixOperator A).toLinearMap = Matrix.toEuclideanLin A := by
  rfl

@[simp] theorem euclideanMatrixOperator_apply {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (A : Matrix ι ι 𝕜)
    (v : EuclideanSpace 𝕜 ι) :
    euclideanMatrixOperator A v = Matrix.toEuclideanLin A v := by
  rfl

theorem euclideanMatrixOperator_adjoint {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (A : Matrix ι ι 𝕜) :
    ContinuousLinearMap.adjoint (euclideanMatrixOperator A) =
      euclideanMatrixOperator (Matrix.conjTranspose A) := by
  apply ContinuousLinearMap.ext
  intro x
  have h : LinearMap.adjoint (Matrix.toEuclideanLin A) =
      Matrix.toEuclideanLin (Matrix.conjTranspose A) := by
    rw [Matrix.toEuclideanLin_eq_toLin_orthonormal]
    exact (Matrix.toLin_conjTranspose (EuclideanSpace.basisFun ι 𝕜)
      (EuclideanSpace.basisFun ι 𝕜) A).symm
  exact congrArg (fun f => f x) h

theorem euclideanMatrixOperator_mul {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (A B : Matrix ι ι 𝕜) :
    euclideanMatrixOperator (A * B) =
      euclideanMatrixOperator A ∘SL euclideanMatrixOperator B := by
  apply ContinuousLinearMap.ext
  intro x
  change Matrix.toEuclideanLin (A * B) x =
    (Matrix.toEuclideanLin A) ((Matrix.toEuclideanLin B) x)
  have h := Matrix.toLin_mul
    (EuclideanSpace.basisFun ι 𝕜).toBasis
    (EuclideanSpace.basisFun ι 𝕜).toBasis
    (EuclideanSpace.basisFun ι 𝕜).toBasis A B
  rw [Matrix.toEuclideanLin_eq_toLin_orthonormal]
  simpa [LinearMap.comp_apply] using congrArg (fun f => f x) h

theorem euclideanMatrixOperator_one {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι] :
    euclideanMatrixOperator (1 : Matrix ι ι 𝕜) = 1 := by
  apply ContinuousLinearMap.ext
  intro x
  change Matrix.toEuclideanLin (1 : Matrix ι ι 𝕜) x = x
  rw [Matrix.toEuclideanLin_eq_toLin_orthonormal]
  simp

noncomputable def euclideanMatrixOperator_selfAdjoint {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (A : Matrix ι ι 𝕜)
    (hA : Matrix.conjTranspose A = A) :
    SelfAdjoint (𝕜 := 𝕜) (E := EuclideanSpace 𝕜 ι) := by
  refine ⟨euclideanMatrixOperator A, ?_⟩
  rw [euclideanMatrixOperator_adjoint, hA]

end LeanPhy.Mathematics.Hilbert

namespace LeanPhy.Mathematics.FiniteMatrixFlow

open LeanPhy.Mathematics

/-- Transport a finite matrix semigroup to bounded operators on the canonical
finite Hilbert space.  This preserves exactly the algebraic flow laws and
does not add a continuity or generator theorem. -/
noncomputable def toHilbertFlow {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (F : Mathematics.FiniteMatrixFlow (𝕜 := 𝕜) ι) :
    Hilbert.Flow (𝕜 := 𝕜) (E := EuclideanSpace 𝕜 ι) where
  op := fun t => Hilbert.euclideanMatrixOperator (F.flow t)
  zero := by
    rw [F.zero]
    exact Hilbert.euclideanMatrixOperator_one
  add := by
    intro t s
    rw [F.add, Hilbert.euclideanMatrixOperator_mul]

@[simp] theorem toHilbertFlow_op {𝕜 : Type*} [RCLike 𝕜]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (F : Mathematics.FiniteMatrixFlow (𝕜 := 𝕜) ι) (t : ℝ) :
    (F.toHilbertFlow).op t = Hilbert.euclideanMatrixOperator (F.flow t) := rfl

end LeanPhy.Mathematics.FiniteMatrixFlow

namespace LeanPhy.Quantum

open LeanPhy.Mathematics

/-- A finite unitary matrix, viewed as a bounded unitary on its canonical
Euclidean Hilbert space.  Both inverse equations are inherited from the
finite-matrix proof, including the right inverse generated by nonsingularity.
-/
noncomputable def FiniteUnitary.toHilbert {ι : Type*} [Fintype ι]
    [DecidableEq ι] (U : FiniteUnitary ι) :
    Hilbert.Unitary (𝕜 := ℂ) (E := EuclideanSpace ℂ ι) where
  op := Hilbert.euclideanMatrixOperator U.op
  left_unitary := by
    rw [Hilbert.euclideanMatrixOperator_adjoint]
    rw [← Hilbert.euclideanMatrixOperator_mul]
    rw [U.unitary]
    exact Hilbert.euclideanMatrixOperator_one
  right_unitary := by
    rw [Hilbert.euclideanMatrixOperator_adjoint]
    rw [← Hilbert.euclideanMatrixOperator_mul]
    rw [U.right_unitary]
    exact Hilbert.euclideanMatrixOperator_one

@[simp] theorem FiniteUnitary.toHilbert_op {ι : Type*} [Fintype ι]
    [DecidableEq ι] (U : FiniteUnitary ι) :
    U.toHilbert.op = Hilbert.euclideanMatrixOperator U.op := by
  rfl

/-- A Hermitian finite matrix can be consumed by the basis-free expectation
API.  The Hermiticity equation is an input certificate, not inferred from a
numeric approximation.
-/
noncomputable def hermitianMatrixToHilbert {ι : Type*} [Fintype ι]
    [DecidableEq ι] (A : Matrix ι ι ℂ)
    (hA : Matrix.conjTranspose A = A) :
    Hilbert.SelfAdjoint (𝕜 := ℂ) (E := EuclideanSpace ℂ ι) :=
  Hilbert.euclideanMatrixOperator_selfAdjoint A hA

end LeanPhy.Quantum
