import LeanPhy.Quantum.Density
import LeanPhy.Quantum.Dirac
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.LinearAlgebra.Matrix.Kronecker
import Mathlib.Tactic

set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false

/-!
# Finite unitary dynamics

This is the reusable finite-dimensional bridge between algebraic operators and
physical evolution.  A `UnitaryOperator` carries `U†U = 1` as an invariant;
the kernel then proves ket-norm preservation, density-matrix validity under
`rho ↦ U rho U†`, and closure under composition.  Time exponentials and
unitarity of a propagator generated by a Hamiltonian remain separate analytic
or differential-equation inputs.
-/

namespace LeanPhy.Quantum

open scoped Matrix ComplexOrder

/-- A unitary matrix indexed by any finite type.  This general form is used
for composite Hilbert spaces, lattice sites and finite internal indices whose
index set is not definitionally a natural-number interval. -/
structure FiniteUnitary (ι : Type*) [Fintype ι] [DecidableEq ι] where
  op : Matrix ι ι ℂ
  unitary : Matrix.conjTranspose op * op = 1

/-! A square finite matrix with a left unitary inverse also has the right
inverse.  Keeping this theorem explicit is useful for similarity arguments:
the public structure stores one equation, while finite-dimensional
non-singularity supplies the other without adding a physical axiom. -/

theorem FiniteUnitary.right_unitary {ι : Type*} [Fintype ι] [DecidableEq ι]
    (U : FiniteUnitary ι) : U.op * Matrix.conjTranspose U.op = 1 := by
  have hdet : IsUnit U.op.det := Matrix.isUnit_det_of_left_inverse U.unitary
  have hright : U.op * U.op⁻¹ = 1 := Matrix.mul_nonsing_inv U.op hdet
  have hadj : Matrix.conjTranspose U.op = U.op⁻¹ := by
    calc
      Matrix.conjTranspose U.op = Matrix.conjTranspose U.op * 1 := by simp
      _ = Matrix.conjTranspose U.op * (U.op * U.op⁻¹) := by rw [hright]
      _ = (Matrix.conjTranspose U.op * U.op) * U.op⁻¹ := by
        rw [Matrix.mul_assoc]
      _ = U.op⁻¹ := by rw [U.unitary, Matrix.one_mul]
  rw [hadj]
  exact hright

/-- The adjoint of a finite unitary is again a finite unitary. -/
def FiniteUnitary.adjoint {ι : Type*} [Fintype ι] [DecidableEq ι]
    (U : FiniteUnitary ι) : FiniteUnitary ι where
  op := Matrix.conjTranspose U.op
  unitary := by
    simpa only [Matrix.conjTranspose_conjTranspose] using U.right_unitary

@[ext] theorem FiniteUnitary.ext {ι : Type*} [Fintype ι] [DecidableEq ι]
    (U V : FiniteUnitary ι) (h : U.op = V.op) : U = V := by
  cases U
  cases V
  cases h
  rfl

/-- Composition of finite unitaries, in the order `after ∘ before`. -/
def FiniteUnitary.compose {ι : Type*} [Fintype ι] [DecidableEq ι]
    (after before : FiniteUnitary ι) : FiniteUnitary ι where
  op := after.op * before.op
  unitary := by
    rw [Matrix.conjTranspose_mul]
    calc
      Matrix.conjTranspose before.op * Matrix.conjTranspose after.op *
          (after.op * before.op) =
          Matrix.conjTranspose before.op *
            (Matrix.conjTranspose after.op * after.op) * before.op := by
              noncomm_ring
      _ = 1 := by rw [after.unitary, Matrix.mul_one, before.unitary]

/-- Tensor products of finite unitaries are unitary on the product index. -/
noncomputable def FiniteUnitary.tensor {ι κ : Type*} [Fintype ι] [DecidableEq ι]
    [Fintype κ] [DecidableEq κ] (U : FiniteUnitary ι) (V : FiniteUnitary κ) :
    FiniteUnitary (ι × κ) where
  op := Matrix.kroneckerMap (fun x y : ℂ => x * y) U.op V.op
  unitary := by
    rw [Matrix.conjTranspose_kronecker]
    rw [← Matrix.mul_kronecker_mul]
    rw [U.unitary, V.unitary, Matrix.one_kronecker_one]

/-- Apply a generic finite-index unitary to a ket. -/
def FiniteUnitary.evolve {ι : Type*} [Fintype ι] [DecidableEq ι]
    (U : FiniteUnitary ι) (v : ι → ℂ) : ι → ℂ := U.op.mulVec v

theorem FiniteUnitary.evolve_inner {ι : Type*} [Fintype ι] [DecidableEq ι]
    (U : FiniteUnitary ι) (v w : ι → ℂ) :
    dotProduct (star (U.evolve v)) (U.evolve w) =
      dotProduct (star v) w := by
  unfold FiniteUnitary.evolve
  rw [Matrix.star_mulVec]
  rw [Matrix.dotProduct_mulVec]
  rw [Matrix.vecMul_vecMul]
  rw [U.unitary, Matrix.vecMul_one]

theorem FiniteUnitary.compose_evolve {ι : Type*} [Fintype ι] [DecidableEq ι]
    (after before : FiniteUnitary ι) (v : ι → ℂ) :
    (after.compose before).evolve v = after.evolve (before.evolve v) := by
  unfold FiniteUnitary.evolve FiniteUnitary.compose
  rw [Matrix.mulVec_mulVec]

/-- Conjugation by a generic finite unitary on a named finite matrix space. -/
def FiniteUnitary.conjugate {ι : Type*} [Fintype ι] [DecidableEq ι]
    (U : FiniteUnitary ι) (rho : Matrix ι ι ℂ) : Matrix ι ι ℂ :=
  U.op * rho * Matrix.conjTranspose U.op

theorem FiniteUnitary.conjugate_trace {ι : Type*} [Fintype ι] [DecidableEq ι]
    (U : FiniteUnitary ι) (rho : Matrix ι ι ℂ) :
    Matrix.trace (U.conjugate rho) = Matrix.trace rho := by
  unfold FiniteUnitary.conjugate
  rw [Matrix.trace_mul_cycle, Matrix.trace_mul_comm]
  rw [U.unitary, Matrix.mul_one]

theorem FiniteUnitary.conjugate_posSemidef {ι : Type*} [Fintype ι]
    [DecidableEq ι] (U : FiniteUnitary ι) (rho : Matrix ι ι ℂ)
    (hrho : rho.PosSemidef) :
    (U.conjugate rho).PosSemidef := by
  unfold FiniteUnitary.conjugate
  exact Matrix.PosSemidef.mul_mul_conjTranspose_same hrho U.op

/-- A finite unitary operator, with the left inverse relation as its invariant. -/
structure UnitaryOperator (n : Nat) where
  op : Operator n
  unitary : Matrix.conjTranspose op * op = 1

/-- View the `Fin n`-indexed API as the generic finite-index API. -/
def UnitaryOperator.toFiniteUnitary {n : Nat} (U : UnitaryOperator n) :
    FiniteUnitary (Fin n) :=
  ⟨U.op, U.unitary⟩

/-- Construct the standard left-inverse form from the right-inverse convention
`A A† = 1` used by many scattering and flavour-physics calculations.  The
finite square-matrix hypothesis is essential: the proof uses the nonsingular
matrix inverse, so this bridge is deliberately finite-dimensional. -/
noncomputable def UnitaryOperator.ofRight {n : Nat} (A : Operator n)
    (h : A * Matrix.conjTranspose A = 1) : UnitaryOperator n where
  op := A
  unitary := by
    have hdet : IsUnit A.det := Matrix.isUnit_det_of_right_inverse h
    have hleft : A⁻¹ * A = 1 := Matrix.nonsing_inv_mul A hdet
    have hadj : Matrix.conjTranspose A = A⁻¹ := by
      calc
        Matrix.conjTranspose A = 1 * Matrix.conjTranspose A := by simp
        _ = (A⁻¹ * A) * Matrix.conjTranspose A := by rw [hleft]
        _ = A⁻¹ * (A * Matrix.conjTranspose A) := by noncomm_ring
        _ = A⁻¹ * 1 := by rw [h]
        _ = A⁻¹ := by simp
    rw [hadj]
    exact hleft

instance : CoeFun (UnitaryOperator n) (fun _ => Operator n) := ⟨UnitaryOperator.op⟩

/-- Apply a finite unitary to a ket. -/
def unitaryEvolve {n : Nat} (U : UnitaryOperator n) (v : Ket n) : Ket n :=
  U.op.mulVec v

theorem unitaryEvolve_inner {n : Nat} (U : UnitaryOperator n)
    (v w : Ket n) :
    braket (unitaryEvolve U v) (unitaryEvolve U w) = braket v w := by
  unfold unitaryEvolve
  change (star (U.op *ᵥ v) ⬝ᵥ (U.op *ᵥ w)) = star v ⬝ᵥ w
  rw [Matrix.star_mulVec]
  rw [Matrix.dotProduct_mulVec]
  rw [Matrix.vecMul_vecMul]
  rw [U.unitary, Matrix.vecMul_one]

theorem unitaryEvolve_normSq {n : Nat} (U : UnitaryOperator n)
    (v : Ket n) :
    braket (unitaryEvolve U v) (unitaryEvolve U v) = braket v v :=
  unitaryEvolve_inner U v v

/-- Conjugation of an operator/state by a finite unitary. -/
def unitaryConjugate {n : Nat} (U : UnitaryOperator n) (rho : State n) : State n :=
  U.op * rho * Matrix.conjTranspose U.op

/-- Heisenberg action on an observable, dual to Schrödinger conjugation. -/
def unitaryObservableConjugate {n : Nat} (U : UnitaryOperator n)
    (A : Observable n) : Observable n :=
  Matrix.conjTranspose U.op * A * U.op

theorem unitary_expectation_duality {n : Nat} (U : UnitaryOperator n)
    (rho : State n) (A : Observable n) :
    expectation (unitaryConjugate U rho) A =
      expectation rho (unitaryObservableConjugate U A) := by
  change Matrix.trace ((U.op * rho * Matrix.conjTranspose U.op) * A) =
    Matrix.trace (rho * (Matrix.conjTranspose U.op * A * U.op))
  rw [show U.op * rho * Matrix.conjTranspose U.op * A =
    (U.op * rho) * (Matrix.conjTranspose U.op * A) by noncomm_ring]
  rw [Matrix.trace_mul_cycle, Matrix.trace_mul_comm]

theorem unitaryConjugate_trace {n : Nat} (U : UnitaryOperator n) (rho : State n) :
    Matrix.trace (unitaryConjugate U rho) = Matrix.trace rho := by
  unfold unitaryConjugate
  rw [Matrix.trace_mul_cycle, Matrix.trace_mul_comm]
  rw [U.unitary, Matrix.mul_one]

theorem unitaryConjugate_posSemidef {n : Nat} (U : UnitaryOperator n)
    (rho : State n) (hrho : rho.PosSemidef) :
    (unitaryConjugate U rho).PosSemidef := by
  unfold unitaryConjugate
  exact Matrix.PosSemidef.mul_mul_conjTranspose_same hrho U.op

theorem unitaryConjugate_isDensity {n : Nat} (U : UnitaryOperator n)
    (rho : State n) (hrho : IsDensity rho) :
    IsDensity (unitaryConjugate U rho) := by
  have hpos : (unitaryConjugate U rho).PosSemidef :=
    unitaryConjugate_posSemidef U rho hrho.2.1
  refine ⟨hpos.isHermitian, hpos, ?_⟩
  exact (unitaryConjugate_trace U rho).trans hrho.2.2

/-- Composition in the order `after ∘ before`. -/
def UnitaryOperator.compose {n : Nat} (after before : UnitaryOperator n) :
    UnitaryOperator n where
  op := after.op * before.op
  unitary := by
    rw [Matrix.conjTranspose_mul]
    calc
      Matrix.conjTranspose before.op * Matrix.conjTranspose after.op *
          (after.op * before.op) =
          Matrix.conjTranspose before.op *
            (Matrix.conjTranspose after.op * after.op) * before.op := by
              noncomm_ring
      _ = 1 := by rw [after.unitary, Matrix.mul_one, before.unitary]

theorem UnitaryOperator.compose_evolve {n : Nat}
    (after before : UnitaryOperator n) (v : Ket n) :
    unitaryEvolve (after.compose before) v =
      unitaryEvolve after (unitaryEvolve before v) := by
  unfold unitaryEvolve UnitaryOperator.compose
  rw [Matrix.mulVec_mulVec]

theorem UnitaryOperator.compose_conjugate {n : Nat}
    (after before : UnitaryOperator n) (rho : State n) :
    unitaryConjugate (after.compose before) rho =
      unitaryConjugate after (unitaryConjugate before rho) := by
  unfold unitaryConjugate UnitaryOperator.compose
  simp only [Matrix.conjTranspose_mul]
  noncomm_ring

end LeanPhy.Quantum
