name = "LeanPhy"
version = "1.0.0"
defaultTargets = ["LeanPhy"]

[[lean_lib]]
name = "LeanPhy"

[[lean_exe]]
name = "leanphy_smoke"
root = "Main"

[[lean_exe]]
name = "leanphy_prototype"
root = "Prototype"

[[lean_exe]]
name = "leanphy_check"
root = "Check"

[[lean_exe]]
name = "leanphy_client_regression"
root = "ClientMain"

[[lean_exe]]
name = "leanphy_strict_client"
root = "StrictClientMain"

[[lean_exe]]
name = "leanphy_init"
root = "Scaffold"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0"

[package]
precompileModules = true
