import Mathlib.Tactic

set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false

/-!
# Derivations on possibly noncommutative algebras

Mathlib's `Derivation` targets commutative algebras.  Matrix-valued gauge
fields need only additivity and the Leibniz rule, so this small structure
provides the algebraic interface used by non-Abelian curvature and discrete
matrix models.  It deliberately carries no smoothness, coordinate or gauge
group assumptions.
-/

namespace LeanPhy.Mathematics

universe u

/-- An additive Leibniz derivation on a (possibly noncommutative) ring. -/
structure AlgebraicDerivation (A : Type u) [Ring A] where
  toFun : A → A
  map_zero' : toFun 0 = 0
  map_add' : ∀ x y, toFun (x + y) = toFun x + toFun y
  leibniz' : ∀ x y, toFun (x * y) = toFun x * y + x * toFun y

instance {A : Type u} [Ring A] : CoeFun (AlgebraicDerivation A) (fun _ => A → A) :=
  ⟨AlgebraicDerivation.toFun⟩

@[simp] theorem AlgebraicDerivation.map_zero {A : Type u} [Ring A]
    (D : AlgebraicDerivation A) : D 0 = 0 := D.map_zero'

@[simp] theorem AlgebraicDerivation.map_add {A : Type u} [Ring A]
    (D : AlgebraicDerivation A) (x y : A) : D (x + y) = D x + D y := D.map_add' x y

theorem AlgebraicDerivation.leibniz {A : Type u} [Ring A]
    (D : AlgebraicDerivation A) (x y : A) : D (x * y) = D x * y + x * D y := D.leibniz' x y

theorem AlgebraicDerivation.map_neg {A : Type u} [Ring A]
    (D : AlgebraicDerivation A) (x : A) : D (-x) = -D x := by
  have h : D x + D (-x) = 0 := by
    simpa using (D.map_add' x (-x)).symm
  exact eq_neg_of_add_eq_zero_right h

theorem AlgebraicDerivation.map_sub {A : Type u} [Ring A]
    (D : AlgebraicDerivation A) (x y : A) : D (x - y) = D x - D y := by
  simp only [sub_eq_add_neg, D.map_add', D.map_neg]

/-- The inner derivation generated by `a`, `x ↦ a x - x a`.  This is the
finite algebraic model behind adjoint actions in matrix gauge theory. -/
def innerDerivation {A : Type u} [Ring A] (a : A) : AlgebraicDerivation A where
  toFun := fun x => a * x - x * a
  map_zero' := by simp only [mul_zero, zero_mul, sub_self]
  map_add' := by
    intro x y
    simp only [mul_add, add_mul]
    noncomm_ring
  leibniz' := by
    intro x y
    noncomm_ring

@[simp] theorem innerDerivation_apply {A : Type u} [Ring A]
    (a x : A) : innerDerivation a x = a * x - x * a := rfl

/- Two inner derivations commute when their generators commute.  The stronger
central-commutator criterion can be added later without changing the public
interface. -/
theorem innerDerivation_commute_of_commute {A : Type u} [Ring A]
    {a b x : A} (h : a * b = b * a) :
    innerDerivation a (innerDerivation b x) =
      innerDerivation b (innerDerivation a x) := by
  simp only [innerDerivation_apply]
  calc
    a * (b * x - x * b) - (b * x - x * b) * a =
        (a * b) * x - a * x * b - b * x * a + x * (b * a) := by
          noncomm_ring
    _ = (b * a) * x - a * x * b - b * x * a + x * (a * b) := by
          rw [h]
    _ = b * (a * x - x * a) - (a * x - x * a) * b := by
          noncomm_ring

end LeanPhy.Mathematics
