import LeanPhy.Mathematics.Poisson
import Mathlib.RingTheory.Ideal.Operations

/-!
# First-class constraints and weak equality

Dirac constraints are useful in classical gauge theory, constrained Hamiltonian
systems, and the classical limit of BRST constructions.  This module records
the algebraic part that can be checked without choosing coordinates or a
continuum phase space:

* constraints generate an ideal in a commutative Poisson algebra;
* first-class closure says brackets of generators lie in that ideal;
* the generated ideal is closed under brackets of two constrained elements;
* weak equality is equality modulo the constraint ideal;
* a Dirac observable is an observable whose bracket with every constraint is
  weakly zero.

No gauge fixing, quotient regularity, Hamiltonian flow, reduction theorem,
constraint classification, or physical interpretation is inferred here.  The
Poisson algebra and every first-class closure proof are explicit inputs.
-/

namespace LeanPhy.Mathematics

universe u v w

/-- A finite or infinite family of constraints in a commutative Poisson algebra.

The `first_class` field is the algebraic first-class condition: the bracket of
any two named generators belongs to the ideal generated by all generators.
Using an ideal rather than a chosen structure-function presentation also covers
field-dependent structure functions and redundant generating families.
-/
structure FirstClassConstraintAlgebra (R : Type u) (A : Type v) (ι : Type w)
    [CommRing R] [CommRing A] [Algebra R A] where
  poisson : PoissonAlgebra R A
  constraint : ι → A
  first_class : ∀ i j,
    poisson (constraint i) (constraint j) ∈
      Ideal.span (Set.range constraint)

namespace FirstClassConstraintAlgebra

variable {R : Type u} {A : Type v} {ι : Type w}
variable [CommRing R] [CommRing A] [Algebra R A]
variable (C : FirstClassConstraintAlgebra R A ι)

/-- The ideal generated by the declared constraints. -/
def constraintIdeal : Ideal A :=
  Ideal.span (Set.range C.constraint)

@[simp] theorem constraint_mem (i : ι) :
    C.constraint i ∈ C.constraintIdeal := by
  exact Ideal.subset_span ⟨i, rfl⟩

theorem bracket_constraint_mem (i j : ι) :
    C.poisson (C.constraint i) (C.constraint j) ∈ C.constraintIdeal := by
  exact C.first_class i j

/-- Bracketing a generator with any constrained element stays constrained. -/
theorem bracket_generator_mem (i : ι) {x : A}
    (hx : x ∈ C.constraintIdeal) :
    C.poisson (C.constraint i) x ∈ C.constraintIdeal := by
  refine Submodule.span_induction (p := fun x _ =>
    C.poisson (C.constraint i) x ∈ C.constraintIdeal) ?_ ?_ ?_ ?_ hx
  · intro x hx
    rcases hx with ⟨j, rfl⟩
    exact C.bracket_constraint_mem i j
  · simp [PoissonAlgebra.bracket_zero_right]
  · intro x y _ _ hx hy
    rw [C.poisson.add_right]
    exact C.constraintIdeal.add_mem hx hy
  · intro a x _ hx
    change C.poisson (C.constraint i) (a * x) ∈ C.constraintIdeal
    rw [C.poisson.leibniz]
    exact C.constraintIdeal.add_mem
      (C.constraintIdeal.mul_mem_left (C.poisson (C.constraint i) a) (by
        exact (show x ∈ C.constraintIdeal from ‹x ∈ C.constraintIdeal›)))
      (C.constraintIdeal.mul_mem_left a hx)

/-- The same closure law with the generator in the right argument. -/
theorem bracket_mem_generator (i : ι) {x : A}
    (hx : x ∈ C.constraintIdeal) :
    C.poisson x (C.constraint i) ∈ C.constraintIdeal := by
  rw [C.poisson.antisymm]
  exact C.constraintIdeal.neg_mem (C.bracket_generator_mem i hx)

/-- The constraint ideal is closed under the Poisson bracket in both arguments. -/
theorem bracket_mem_constraintIdeal {x y : A}
    (hx : x ∈ C.constraintIdeal) (hy : y ∈ C.constraintIdeal) :
    C.poisson x y ∈ C.constraintIdeal := by
  refine Submodule.span_induction (p := fun x _ =>
    C.poisson x y ∈ C.constraintIdeal) ?_ ?_ ?_ ?_ hx
  · intro x hx
    rcases hx with ⟨i, rfl⟩
    exact C.bracket_generator_mem i hy
  · simp [PoissonAlgebra.bracket_zero_left]
  · intro x z _ _ hx hz
    rw [C.poisson.add_left]
    exact C.constraintIdeal.add_mem hx hz
  · intro a x _ hx
    change C.poisson (a * x) y ∈ C.constraintIdeal
    rw [PoissonAlgebra.bracket_mul_left]
    exact C.constraintIdeal.add_mem
      (C.constraintIdeal.mul_mem_left a hx)
      (C.constraintIdeal.mul_mem_left (C.poisson a y) (by
        exact (show x ∈ C.constraintIdeal from ‹x ∈ C.constraintIdeal›)))

/-- Equality modulo the generated constraint ideal (Dirac's weak equality). -/
def WeaklyEqual (x y : A) : Prop :=
  x - y ∈ C.constraintIdeal

@[simp] theorem weaklyEqual_refl (x : A) : C.WeaklyEqual x x := by
  simp [WeaklyEqual]

theorem weaklyEqual_symm {x y : A} (h : C.WeaklyEqual x y) :
    C.WeaklyEqual y x := by
  change y - x ∈ C.constraintIdeal
  rw [← neg_sub]
  exact C.constraintIdeal.neg_mem h

theorem weaklyEqual_trans {x y z : A}
    (hxy : C.WeaklyEqual x y) (hyz : C.WeaklyEqual y z) :
    C.WeaklyEqual x z := by
  change x - z ∈ C.constraintIdeal
  have h := C.constraintIdeal.add_mem hxy hyz
  rw [sub_add_sub_cancel x y z] at h
  exact h

/-- A constraint is weakly zero precisely when it belongs to the ideal. -/
theorem weaklyEqual_zero_iff {x : A} :
    C.WeaklyEqual x 0 ↔ x ∈ C.constraintIdeal := by
  simp [WeaklyEqual]

/-- A Dirac observable has weakly vanishing bracket with every constraint. -/
def IsDiracObservable (f : A) : Prop :=
  ∀ {c : A}, c ∈ C.constraintIdeal → C.poisson c f ∈ C.constraintIdeal

/-- Every named first-class constraint is a Dirac observable. -/
theorem constraint_isDiracObservable (i : ι) :
    C.IsDiracObservable (C.constraint i) := by
  intro c hc
  exact C.bracket_mem_generator i hc

@[simp] theorem dirac_zero : C.IsDiracObservable 0 := by
  intro c hc
  simp [C.poisson.bracket_zero_right]

theorem dirac_add {f g : A}
    (hf : C.IsDiracObservable f) (hg : C.IsDiracObservable g) :
    C.IsDiracObservable (f + g) := by
  intro c hc
  rw [C.poisson.add_right]
  exact C.constraintIdeal.add_mem (hf hc) (hg hc)

theorem dirac_smul (r : R) {f : A}
    (hf : C.IsDiracObservable f) :
    C.IsDiracObservable (r • f) := by
  intro c hc
  rw [C.poisson.smul_right]
  rw [Algebra.smul_def]
  exact C.constraintIdeal.mul_mem_left (algebraMap R A r) (hf hc)

theorem dirac_mul {f g : A}
    (hf : C.IsDiracObservable f) (hg : C.IsDiracObservable g) :
    C.IsDiracObservable (f * g) := by
  intro c hc
  rw [C.poisson.leibniz]
  exact C.constraintIdeal.add_mem
    (C.constraintIdeal.mul_mem_right g (hf hc))
    (C.constraintIdeal.mul_mem_left f (hg hc))

/-- Dirac observables form a Poisson subalgebra at the level of propositions.

The proof is the Jacobi identity plus first-class closure.  This is the useful
algebraic seed for reduced observables; a quotient, gauge fixing, and a
physical reduction map still need separate model-specific data.
-/
theorem dirac_bracket {f g : A}
    (hf : C.IsDiracObservable f) (hg : C.IsDiracObservable g) :
    C.IsDiracObservable (C.poisson f g) := by
  intro c hc
  have hJ := C.poisson.jacobi c f g
  have hcf : C.poisson c f ∈ C.constraintIdeal := hf hc
  have hcg : C.poisson c g ∈ C.constraintIdeal := hg hc
  have hsecond : C.poisson f (C.poisson c g) ∈ C.constraintIdeal := by
    rw [C.poisson.antisymm]
    exact C.constraintIdeal.neg_mem (hf hcg)
  have hgc : C.poisson g c = -C.poisson c g := C.poisson.antisymm g c
  have hthird : C.poisson g (C.poisson c f) ∈ C.constraintIdeal := by
    rw [C.poisson.antisymm]
    exact C.constraintIdeal.neg_mem (hg hcf)
  have hsecond' : C.poisson f (C.poisson g c) ∈ C.constraintIdeal := by
    rw [hgc, PoissonAlgebra.bracket_neg_right]
    exact C.constraintIdeal.neg_mem hsecond
  have hsum : C.poisson c (C.poisson f g) ∈ C.constraintIdeal := by
    have hrest : C.poisson f (C.poisson g c) +
        C.poisson g (C.poisson c f) ∈ C.constraintIdeal :=
      C.constraintIdeal.add_mem hsecond' hthird
    have hJ' : C.poisson c (C.poisson f g) +
        (C.poisson f (C.poisson g c) + C.poisson g (C.poisson c f)) = 0 := by
      simpa [add_assoc] using hJ
    have htarget : -C.poisson c (C.poisson f g) =
        C.poisson f (C.poisson g c) + C.poisson g (C.poisson c f) :=
      (neg_eq_iff_add_eq_zero).2 hJ'
    have hneg : -C.poisson c (C.poisson (f) g) ∈ C.constraintIdeal := by
      rw [htarget]
      exact hrest
    simpa using C.constraintIdeal.neg_mem hneg
  exact hsum

end FirstClassConstraintAlgebra

end LeanPhy.Mathematics
