import LeanPhy.Mathematics.Approximation
import Mathlib.Data.Matrix.Basic
import Lean.Data.Json

/-!
# Proof-producing external certificates

Numerical and computer-algebra programs are useful for discovering a matrix
identity, an eigenpair residual, or a discretisation bound.  Their output is
data, however, and must not become a proof merely because a program returned
`true`.  This module makes the trust boundary explicit:

* an external producer supplies an `Envelope` containing payload data and
  provenance;
* a Lean-side `CertificateChecker` states what the payload means and proves a
  soundness theorem;
* only `VerifiedCertificate.proof` may be used as a theorem in a package.

The checker may be implemented by reflection, a verified parser, or ordinary
Lean lemmas.  The payload itself is never trusted, and the metadata is never
used as evidence.  This interface is intentionally domain-neutral so the same
boundary can serve finite matrices, lattice PDE residuals, transfer matrices,
and truncated field calculations.
-/

namespace LeanPhy.Mathematics

universe u v

open Lean

/-- Provenance attached to a certificate payload.  These fields are audit
metadata only; none of them contributes to a theorem. -/
structure CertificateMetadata where
  producer : String
  format : String
  digest : String
  source : String
  deriving Repr, ToJson, FromJson

/-- The serializable object that an external tool is expected to emit.  A
    parser may construct this value from JSON, CSV, or a CAS-specific format;
    the payload becomes useful only after a checker accepts it. -/
structure CertificateEnvelope (C : Type u) where
  metadata : CertificateMetadata
  payload : C

/- JSON keeps the payload untyped until the caller supplies its codec.  This
   small raw envelope is generated by Lean's standard JSON derivation and
   avoids requiring a codec at the definition site of the trust boundary. -/
structure JsonCertificateEnvelope (C : Type u) where
  metadata : CertificateMetadata
  payload : Json
  deriving ToJson, FromJson

/-- Standard JSON boundary for a decoded certificate envelope.  The payload
    codec is an explicit typeclass requirement; a JSON parser never chooses a
    theorem or a checker implicitly. -/
def encodeEnvelope {C : Type u} [ToJson C]
    (envelope : CertificateEnvelope C) : Json :=
  toJson ({ metadata := envelope.metadata, payload := toJson envelope.payload } :
    JsonCertificateEnvelope C)

def decodeEnvelope {C : Type u} [FromJson C]
    (json : Json) : Except String (CertificateEnvelope C) :=
  match fromJson? (α := JsonCertificateEnvelope C) json with
  | .error message => .error message
  | .ok raw =>
    match fromJson? (α := C) raw.payload with
    | .error message => .error message
    | .ok payload => .ok { metadata := raw.metadata, payload := payload }

/-- A sound Lean checker for one proposition and one certificate payload type.
    `check` is a proposition, rather than a runtime Boolean, so a checker
    cannot silently turn an unverified computation into evidence. -/
structure CertificateChecker (P : Prop) (C : Type u) where
  check : C → Prop
  sound : ∀ {c : C}, check c → P

/-- A certificate together with the proof that the checker accepted it. -/
structure VerifiedCertificate {P : Prop} {C : Type u}
    (checker : CertificateChecker P C) where
  envelope : CertificateEnvelope C
  checked : checker.check envelope.payload

namespace VerifiedCertificate

variable {P : Prop} {C : Type u}
variable (checker : CertificateChecker P C)

/-- The only theorem-producing projection from an external certificate. -/
theorem proof (certificate : VerifiedCertificate checker) : P :=
  checker.sound certificate.checked

def metadata (certificate : VerifiedCertificate checker) : CertificateMetadata :=
  certificate.envelope.metadata

def payload (certificate : VerifiedCertificate checker) : C :=
  certificate.envelope.payload

end VerifiedCertificate

/-- Validate an envelope after a Lean proof of the checker predicate has been
    supplied.  External JSON parsing therefore remains separate from theorem
    construction. -/
def verifyEnvelope {P : Prop} {C : Type u}
    (checker : CertificateChecker P C) (envelope : CertificateEnvelope C)
    (checked : checker.check envelope.payload) : VerifiedCertificate checker :=
  { envelope := envelope, checked := checked }

/-- A small adapter for checkers whose payload already contains a proof.  It
    is useful while migrating an existing formal development; replacing the
    payload with a reflected syntax tree later does not change the public
    `VerifiedCertificate` API. -/
structure ProofPayload (P : Prop) where
  marker : String
  proof : P

def proofPayloadChecker (P : Prop) : CertificateChecker P (ProofPayload P) where
  check _ := P
  sound := fun {_payload} h => h

def verifyProofPayload {P : Prop} (metadata : CertificateMetadata)
    (payload : ProofPayload P) :
    VerifiedCertificate (proofPayloadChecker P) :=
  verifyEnvelope (proofPayloadChecker P) { metadata := metadata, payload := payload }
    payload.proof

/-! A concrete matrix equality adapter.  It is deliberately exact: a CAS may
    emit an equality witness, but Lean still checks that witness before any
    package can call it a theorem. -/

structure MatrixEqualityPayload {ι : Type u} {R : Type v}
    (lhs rhs : Matrix ι ι R) where
  marker : String

def matrixEqualityChecker {ι : Type u} {R : Type v}
    {lhs rhs : Matrix ι ι R} :
    CertificateChecker (lhs = rhs) (MatrixEqualityPayload lhs rhs) where
  check _ := lhs = rhs
  sound := fun {_payload} h => h

def verifyMatrixEquality {ι : Type u} {R : Type v}
    {lhs rhs : Matrix ι ι R} (metadata : CertificateMetadata)
    (payload : MatrixEqualityPayload lhs rhs) (checked : lhs = rhs) :
    VerifiedCertificate (matrixEqualityChecker (lhs := lhs) (rhs := rhs)) :=
  verifyEnvelope (matrixEqualityChecker (lhs := lhs) (rhs := rhs))
    { metadata := metadata, payload := payload } checked

/-! Domain aliases make the interface discoverable without duplicating its
    soundness contract. -/

namespace Quantum
abbrev ExternalCertificate {P : Prop} {C : Type*}
    (checker : LeanPhy.Mathematics.CertificateChecker P C) :=
  LeanPhy.Mathematics.VerifiedCertificate checker
end Quantum

namespace FieldTheory
abbrev ExternalCertificate {P : Prop} {C : Type*}
    (checker : LeanPhy.Mathematics.CertificateChecker P C) :=
  LeanPhy.Mathematics.VerifiedCertificate checker
end FieldTheory

namespace Condensed
abbrev ExternalCertificate {P : Prop} {C : Type*}
    (checker : LeanPhy.Mathematics.CertificateChecker P C) :=
  LeanPhy.Mathematics.VerifiedCertificate checker
end Condensed

namespace GaugeTheory
abbrev ExternalCertificate {P : Prop} {C : Type*}
    (checker : LeanPhy.Mathematics.CertificateChecker P C) :=
  LeanPhy.Mathematics.VerifiedCertificate checker
end GaugeTheory

namespace StatMech
abbrev ExternalCertificate {P : Prop} {C : Type*}
    (checker : LeanPhy.Mathematics.CertificateChecker P C) :=
  LeanPhy.Mathematics.VerifiedCertificate checker
end StatMech

namespace Classical
abbrev ExternalCertificate {P : Prop} {C : Type*}
    (checker : LeanPhy.Mathematics.CertificateChecker P C) :=
  LeanPhy.Mathematics.VerifiedCertificate checker
end Classical

end LeanPhy.Mathematics
