import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Tactic

/-!
# Finite linear evolution and semigroup interface

Hamiltonian evolution, linear response, finite-volume transfer steps, tangent
systems and truncated kinetic equations all use the same algebraic law

`U (t + s) = U t * U s`.

This module exposes that law without claiming that a matrix family solves a
continuous ODE.  The latter requires a derivative and regularity theorem and
is deliberately kept as a separate obligation.  The canonical matrix
exponential instance is available over every `RCLike` scalar, so real classical
or relativistic systems and complex quantum systems use the same API.
-/

namespace LeanPhy.Mathematics

open NormedSpace
open scoped Matrix Matrix.Norms.Operator

universe u v

variable {𝕜 : Type u} [RCLike 𝕜]

/-- A finite-dimensional evolution family with its algebraic semigroup laws.
The flow is not assumed to be unitary, positive, continuous or generated by a
particular differential equation; those properties belong in separate
certificates. -/
structure FiniteMatrixFlow (ι : Type v) [Fintype ι] [DecidableEq ι] where
  flow : ℝ → Matrix ι ι 𝕜
  zero : flow 0 = 1
  add : ∀ t s, flow (t + s) = flow t * flow s

namespace FiniteMatrixFlow

variable {ι : Type v} [Fintype ι] [DecidableEq ι]

@[simp] theorem flow_zero (F : FiniteMatrixFlow (𝕜 := 𝕜) ι) :
    F.flow 0 = 1 := F.zero

theorem flow_add (F : FiniteMatrixFlow (𝕜 := 𝕜) ι) (t s : ℝ) :
    F.flow (t + s) = F.flow t * F.flow s := F.add t s

/-- Apply a finite evolution family to a state vector. -/
def evolve (F : FiniteMatrixFlow (𝕜 := 𝕜) ι) (t : ℝ)
    (v : ι → 𝕜) : ι → 𝕜 := F.flow t *ᵥ v

@[simp] theorem evolve_zero (F : FiniteMatrixFlow (𝕜 := 𝕜) ι) (v : ι → 𝕜) :
    F.evolve 0 v = v := by
  unfold evolve
  rw [F.zero, Matrix.one_mulVec]

theorem evolve_add (F : FiniteMatrixFlow (𝕜 := 𝕜) ι) (t s : ℝ)
    (v : ι → 𝕜) :
    F.evolve (t + s) v = F.evolve t (F.evolve s v) := by
  unfold evolve
  rw [F.add, Matrix.mulVec_mulVec]

/-! The canonical flow generated by one finite matrix. -/

noncomputable def exponential (A : Matrix ι ι 𝕜) :
    FiniteMatrixFlow (𝕜 := 𝕜) ι where
  flow := fun t => by
    letI : NormedRing (Matrix ι ι 𝕜) := Matrix.linftyOpNormedRing
    letI : NormedAlgebra ℚ (Matrix ι ι 𝕜) := Matrix.linftyOpNormedAlgebra
    exact NormedSpace.exp ((algebraMap ℝ 𝕜 t) • A)
  zero := by
    letI : NormedRing (Matrix ι ι 𝕜) := Matrix.linftyOpNormedRing
    letI : NormedAlgebra ℚ (Matrix ι ι 𝕜) := Matrix.linftyOpNormedAlgebra
    simp
  add := by
    intro t s
    letI : NormedRing (Matrix ι ι 𝕜) := Matrix.linftyOpNormedRing
    letI : NormedAlgebra ℚ (Matrix ι ι 𝕜) := Matrix.linftyOpNormedAlgebra
    rw [show (algebraMap ℝ 𝕜 (t + s)) • A =
        (algebraMap ℝ 𝕜 t) • A + (algebraMap ℝ 𝕜 s) • A by
      rw [map_add, add_smul]]
    rw [Matrix.exp_add_of_commute _ _]
    change (((algebraMap ℝ 𝕜 t) • A) * ((algebraMap ℝ 𝕜 s) • A)) =
      (((algebraMap ℝ 𝕜 s) • A) * ((algebraMap ℝ 𝕜 t) • A))
    simp [Matrix.smul_mul, Matrix.mul_smul, smul_smul, mul_comm]

@[simp] theorem exponential_flow (A : Matrix ι ι 𝕜) (t : ℝ) :
    (exponential A).flow t =
      NormedSpace.exp ((algebraMap ℝ 𝕜 t) • A) := rfl

theorem exponential_neg_mul (A : Matrix ι ι 𝕜) (t : ℝ) :
    (exponential A).flow (-t) * (exponential A).flow t = 1 := by
  letI : NormedRing (Matrix ι ι 𝕜) := Matrix.linftyOpNormedRing
  letI : NormedAlgebra ℚ (Matrix ι ι 𝕜) := Matrix.linftyOpNormedAlgebra
  rw [exponential_flow, exponential_flow]
  have hneg : (algebraMap ℝ 𝕜 (-t)) • A =
      -((algebraMap ℝ 𝕜 t) • A) := by
    rw [map_neg, neg_smul]
  rw [hneg, Matrix.exp_neg, Matrix.nonsing_inv_eq_ringInverse]
  have hu : IsUnit (NormedSpace.exp ((algebraMap ℝ 𝕜 t) • A)) :=
    Matrix.isUnit_exp _
  rw [Ring.inverse_of_isUnit hu]
  exact Units.inv_mul hu.unit

theorem exponential_mul_neg (A : Matrix ι ι 𝕜) (t : ℝ) :
    (exponential A).flow t * (exponential A).flow (-t) = 1 := by
  letI : NormedRing (Matrix ι ι 𝕜) := Matrix.linftyOpNormedRing
  letI : NormedAlgebra ℚ (Matrix ι ι 𝕜) := Matrix.linftyOpNormedAlgebra
  rw [exponential_flow, exponential_flow]
  have hneg : (algebraMap ℝ 𝕜 (-t)) • A =
      -((algebraMap ℝ 𝕜 t) • A) := by
    rw [map_neg, neg_smul]
  rw [hneg, Matrix.exp_neg, Matrix.nonsing_inv_eq_ringInverse]
  have hu : IsUnit (NormedSpace.exp ((algebraMap ℝ 𝕜 t) • A)) :=
    Matrix.isUnit_exp _
  rw [Ring.inverse_of_isUnit hu]
  exact Units.mul_inv hu.unit

theorem exponential_evolve_neg (A : Matrix ι ι 𝕜) (t : ℝ)
    (v : ι → 𝕜) :
    (exponential A).evolve (-t) ((exponential A).evolve t v) = v := by
  unfold evolve
  rw [Matrix.mulVec_mulVec, exponential_neg_mul, Matrix.one_mulVec]

end FiniteMatrixFlow

/-! A short alias makes the interface discoverable from physics modules. -/

abbrev LinearEvolution (𝕜 : Type u) [RCLike 𝕜] (ι : Type v)
    [Fintype ι] [DecidableEq ι] := FiniteMatrixFlow (𝕜 := 𝕜) ι

end LeanPhy.Mathematics
