import LeanPhy.Mathematics.FiniteProcess

/-!
# Proof-preserving physical models and model maps

Different areas often use different names for the same research object: a
quantum channel, a finite Markov step, a lattice update, or a truncated mode
evolution.  `PhysicalModel` gives these objects one small contract.  A model
contains an admissible state predicate, one proof-preserving step, and a typed
observable evaluation function.

`ModelMap` is the reusable bridge between two such models.  It carries a
state map, a pullback of observables, and proofs that both dynamics and
observables commute.  The bridge is therefore stronger than a metadata link:
the kernel checks that a finite surrogate really simulates the declared model
for every finite iterate.  No continuum limit or physical interpretation is
inferred; those remain explicit assumptions or approximation certificates.
-/

namespace LeanPhy.Mathematics

universe u v w

structure PhysicalModel (R : Type w) where
  State : Type u
  valid : State → Prop
  step : Process State valid
  Observable : Type v
  evaluate : State → Observable → R

namespace PhysicalModel

variable {R : Type w} (M : PhysicalModel R)

/- A named constructor keeps domain adapters small: they only need to expose
   the state predicate, its proof-preserving process, and the readout. -/
def fromProcess {S : Type u} {Obs : Type v}
    (valid : S → Prop) (step : Process S valid)
    (evaluate : S → Obs → R) : PhysicalModel R :=
  { State := S, valid := valid, step := step,
    Observable := Obs, evaluate := evaluate }

/-- Finite-time evolution generated by the model's proof-preserving step. -/
def evolve (n : Nat) (s : M.State) : M.State := Process.iterate M.step n s

@[simp] theorem evolve_zero (s : M.State) : M.evolve 0 s = s := rfl

@[simp] theorem evolve_succ (n : Nat) (s : M.State) :
    M.evolve (n + 1) s = M.step (M.evolve n s) := rfl

theorem evolve_valid (n : Nat) {s : M.State} (hs : M.valid s) :
    M.valid (M.evolve n s) :=
  Process.iterate_valid M.step n hs

theorem evolve_add (m n : Nat) (s : M.State) :
    M.evolve (m + n) s = M.evolve m (M.evolve n s) :=
  Process.iterate_add M.step m n s

/-! Independent subsystems share the same model contract.  The observable
   codomain is a product so a product model can retain both readouts without
   inventing a scalar pairing convention. -/

def product (M N : PhysicalModel R) : PhysicalModel (R × R) where
  State := M.State × N.State
  valid := fun p => M.valid p.1 ∧ N.valid p.2
  step := Process.parallel M.step N.step
  Observable := M.Observable × N.Observable
  evaluate := fun p o => (M.evaluate p.1 o.1, N.evaluate p.2 o.2)

@[simp] theorem product_evaluate (M N : PhysicalModel R)
    (s : M.State) (t : N.State) (o : M.Observable) (p : N.Observable) :
    (M.product N).evaluate (s, t) (o, p) =
      (M.evaluate s o, N.evaluate t p) := rfl

theorem product_evolve (M N : PhysicalModel R) (n : Nat)
    (s : M.State) (t : N.State) :
    (M.product N).evolve n (s, t) = (M.evolve n s, N.evolve n t) :=
  Process.iterate_parallel M.step N.step n s t

end PhysicalModel

/-! ## Dynamics- and observable-preserving model maps -/

structure ModelMap {R : Type w} (M N : PhysicalModel R) where
  state : StateMap M.State N.State M.valid N.valid
  pullback : N.Observable → M.Observable
  step_commutes : ∀ s, M.valid s →
    state (M.step s) = N.step (state s)
  evaluate_commutes : ∀ s, M.valid s → ∀ o,
    N.evaluate (state s) o = M.evaluate s (pullback o)

namespace ModelMap

variable {R : Type w} {M N O : PhysicalModel R}

/- This constructor is intentionally explicit about both commuting laws.  A
   state map that merely preserves validity is not yet a model adapter. -/
def fromStateMap (state : StateMap M.State N.State M.valid N.valid)
    (pullback : N.Observable → M.Observable)
    (step_commutes : ∀ s, M.valid s →
      state (M.step s) = N.step (state s))
    (evaluate_commutes : ∀ s, M.valid s → ∀ o,
      N.evaluate (state s) o = M.evaluate s (pullback o)) :
    ModelMap M N :=
  { state, pullback, step_commutes, evaluate_commutes }

theorem map_valid (F : ModelMap M N) {s : M.State} (hs : M.valid s) :
    N.valid (F.state s) :=
  F.state.preserves s hs

def identity (M : PhysicalModel R) : ModelMap M M where
  state := StateMap.identity M.State M.valid
  pullback := id
  step_commutes := by intro s _; rfl
  evaluate_commutes := by intro s _ o; rfl

def compose (after : ModelMap N O) (before : ModelMap M N) : ModelMap M O where
  state := StateMap.compose after.state before.state
  pullback := fun o => before.pullback (after.pullback o)
  step_commutes := by
    intro s hs
    change after.state (before.state (M.step s)) =
      O.step (after.state (before.state s))
    rw [before.step_commutes s hs]
    exact after.step_commutes (before.state s)
      (before.state.preserves s hs)
  evaluate_commutes := by
    intro s hs o
    change O.evaluate (after.state (before.state s)) o =
      M.evaluate s (before.pullback (after.pullback o))
    rw [after.evaluate_commutes (before.state s)
      (before.state.preserves s hs) o]
    exact before.evaluate_commutes s hs (after.pullback o)

theorem compose_state_apply (after : ModelMap N O) (before : ModelMap M N)
    (s : M.State) :
    (compose after before).state s = after.state (before.state s) := rfl

theorem compose_pullback_apply (after : ModelMap N O) (before : ModelMap M N)
    (o : O.Observable) :
    (compose after before).pullback o = before.pullback (after.pullback o) := rfl

theorem compose_assoc {P : PhysicalModel R} (third : ModelMap O P)
    (second : ModelMap N O) (first : ModelMap M N) :
    compose third (compose second first) =
      compose (compose third second) first := by
  cases third
  cases second
  cases first
  rfl

theorem identity_left (F : ModelMap M N) :
    compose (identity N) F = F := by
  cases F
  rfl

theorem identity_right (F : ModelMap M N) :
    compose F (identity M) = F := by
  cases F
  rfl

/- The central refinement theorem: a model map commutes with every finite
   iterate, so a finite truncation or domain adapter can be used repeatedly
   without re-proving the simulation step at each time. -/
theorem iterate_commutes (F : ModelMap M N) (n : Nat) (s : M.State)
    (hs : M.valid s) :
    F.state (M.evolve n s) = N.evolve n (F.state s) := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [PhysicalModel.evolve_succ, PhysicalModel.evolve_succ]
      rw [F.step_commutes (M.evolve n s) (M.evolve_valid n hs)]
      exact congrArg N.step ih

theorem evaluate_after_iterate (F : ModelMap M N) (n : Nat)
    (s : M.State) (hs : M.valid s) (o : N.Observable) :
    N.evaluate (F.state (M.evolve n s)) o =
      M.evaluate (M.evolve n s) (F.pullback o) :=
  F.evaluate_commutes (M.evolve n s) (M.evolve_valid n hs) o

/-- Reuse the existing observable transport interface without changing semantics. -/
def toObservableTransport (F : ModelMap M N) :
    ObservableTransport F.state M.Observable N.Observable R M.evaluate N.evaluate where
  pullback := F.pullback
  compatible := F.evaluate_commutes

/-- The target's actual trajectory has exactly the pulled-back readout. -/
theorem trajectory_evaluate (F : ModelMap M N) (n : Nat)
    (s : M.State) (hs : M.valid s) (o : N.Observable) :
    N.evaluate (N.evolve n (F.state s)) o =
      M.evaluate (M.evolve n s) (F.pullback o) := by
  rw [← F.iterate_commutes n s hs]
  exact F.evaluate_after_iterate n s hs o

/-- Pull a target conservation law back to the source model. -/
def pullInvariant {Q : Type*} (F : ModelMap M N) (I : Invariant N.step Q) :
    Invariant M.step Q where
  quantity := fun s => I.quantity (F.state s)
  preserved := by
    intro s hs
    rw [F.step_commutes s hs]
    exact I.preserved (F.state s) (F.state.preserves s hs)

def product {M₁ N₁ M₂ N₂ : PhysicalModel R}
    (left : ModelMap M₁ N₁) (right : ModelMap M₂ N₂) :
    ModelMap (M₁.product M₂) (N₁.product N₂) where
  state := StateMap.product left.state right.state
  pullback := fun o => (left.pullback o.1, right.pullback o.2)
  step_commutes := by
    intro s hs
    apply congrArg₂ Prod.mk
    · exact left.step_commutes s.1 hs.1
    · exact right.step_commutes s.2 hs.2
  evaluate_commutes := by
    intro s hs o
    apply congrArg₂ Prod.mk
    · exact left.evaluate_commutes s.1 hs.1 o.1
    · exact right.evaluate_commutes s.2 hs.2 o.2

@[simp] theorem product_state_apply {M₁ N₁ M₂ N₂ : PhysicalModel R}
    (left : ModelMap M₁ N₁) (right : ModelMap M₂ N₂)
    (s : M₁.State) (t : M₂.State) :
    (product left right).state (s, t) = (left.state s, right.state t) := rfl

end ModelMap

end LeanPhy.Mathematics
