import LeanPhy.Classical.PolynomialPhaseSpace
import Mathlib.Algebra.MvPolynomial.Derivation
import Mathlib.Tactic

set_option maxHeartbeats 3200000
set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false

/-!
# Algebraic variational equations

This module adds a small, reusable Euler--Lagrange layer without pretending to
solve the analytic calculus of variations.  A jet polynomial has slots for a
field, its first time derivative and its second time derivative.  The total
derivative is a polynomial derivation sending these slots to the next ones.
Consequently an Euler--Lagrange residual is an ordinary polynomial that
can be normalized by the kernel.  The same construction applies to a finite
collection of mechanical coordinates, lattice fields, or truncated field
components; smoothness, integration by parts, boundary conditions and
infinite-dimensional limits remain explicit hypotheses of later layers.
-/

namespace LeanPhy.Classical

open LeanPhy.Mathematics

/-! ## One-component jet algebra -/

/-- A polynomial jet `(q, v, a)` for a single finite-dimensional degree of
freedom.  The three slots stand for a coordinate, velocity and acceleration. -/
abbrev JetPolynomial := MvPolynomial (Fin 3) ℝ

noncomputable def jetQ : JetPolynomial := MvPolynomial.X 0
noncomputable def jetV : JetPolynomial := MvPolynomial.X 1
noncomputable def jetA : JetPolynomial := MvPolynomial.X 2

noncomputable def jetQDerivative : PhysicsDerivation ℝ JetPolynomial :=
  MvPolynomial.pderiv 0

noncomputable def jetVDerivative : PhysicsDerivation ℝ JetPolynomial :=
  MvPolynomial.pderiv 1

/-- The formal total time derivative `D_t q = v`, `D_t v = a`, `D_t a = 0`.
It is generated by the polynomial derivation constructor, so the Leibniz rule
is part of the type rather than an extra physics axiom. -/
noncomputable def totalDerivative : PhysicsDerivation ℝ JetPolynomial :=
  MvPolynomial.mkDerivation ℝ (fun i =>
    if i = 0 then jetV else if i = 1 then jetA else 0)

@[simp] theorem totalDerivative_q : totalDerivative jetQ = jetV := by
  simp [totalDerivative, jetQ]

@[simp] theorem totalDerivative_v : totalDerivative jetV = jetA := by
  simp [totalDerivative, jetV, jetA]

@[simp] theorem totalDerivative_a : totalDerivative jetA = 0 := by
  simp [totalDerivative, jetA]

/-- The algebraic Euler--Lagrange residual
`∂L/∂q - D_t (∂L/∂v)`.  An equation of motion is the explicit assertion that
this residual vanishes for the chosen model and hypotheses. -/
noncomputable def eulerLagrangeResidual (L : JetPolynomial) : JetPolynomial :=
  jetQDerivative L - totalDerivative (jetVDerivative L)

/-- Normalized harmonic-oscillator Lagrangian `L = (v²-q²)/2`. -/
noncomputable def oscillatorLagrangian : JetPolynomial :=
  (1 / 2 : ℝ) • (jetV * jetV) - (1 / 2 : ℝ) • (jetQ * jetQ)

/- The formal Euler--Lagrange equation is `q + a = 0`.  This is an identity in
the jet algebra; no trajectory or existence theorem is inferred. -/
theorem oscillator_euler_lagrange :
    eulerLagrangeResidual oscillatorLagrangian = -(jetQ + jetA) := by
  simp [eulerLagrangeResidual, oscillatorLagrangian, jetQDerivative,
    jetVDerivative, totalDerivative, jetQ, jetV, jetA]
  module

/-! ## Finite-component fields -/

/-- Jet polynomials for a finite family of field or lattice components.  The
first component of the variable is the field label; the second is the jet slot
`0=q`, `1=v`, `2=a`. -/
abbrev FieldJetPolynomial (ι : Type) := MvPolynomial (ι × Fin 3) ℝ

noncomputable def fieldJetVar {ι : Type} [DecidableEq ι]
    (x : ι) (slot : Fin 3) : FieldJetPolynomial ι :=
  MvPolynomial.X (x, slot)

/-- Total derivative acting on the jet of one selected field component.  Other
components are held fixed, which is the algebraic core of a componentwise
Euler--Lagrange calculation. -/
noncomputable def fieldTotalDerivative {ι : Type} [DecidableEq ι]
    (x : ι) : PhysicsDerivation ℝ (FieldJetPolynomial ι) :=
  MvPolynomial.mkDerivation ℝ (fun p =>
    if p.1 = x ∧ p.2 = 0 then fieldJetVar p.1 1
    else if p.1 = x ∧ p.2 = 1 then fieldJetVar p.1 2
    else 0)

@[simp] theorem fieldTotalDerivative_q {ι : Type} [DecidableEq ι] (x : ι) :
    fieldTotalDerivative x (fieldJetVar x 0) = fieldJetVar x 1 := by
  simp [fieldTotalDerivative, fieldJetVar]

@[simp] theorem fieldTotalDerivative_v {ι : Type} [DecidableEq ι] (x : ι) :
    fieldTotalDerivative x (fieldJetVar x 1) = fieldJetVar x 2 := by
  simp [fieldTotalDerivative, fieldJetVar]

@[simp] theorem fieldTotalDerivative_other {ι : Type} [DecidableEq ι]
    {x y : ι} (h : y ≠ x) (slot : Fin 3) :
    fieldTotalDerivative x (fieldJetVar y slot) = 0 := by
  simp [fieldTotalDerivative, fieldJetVar, h]

/-! The componentwise residual uses the field label as a typed derivative
index.  A Lagrangian may contain all components; differentiating in `x` only
selects the corresponding Euler equation. -/

noncomputable def fieldEulerLagrangeResidual {ι : Type} [DecidableEq ι]
    (x : ι) (L : FieldJetPolynomial ι) : FieldJetPolynomial ι :=
  MvPolynomial.pderiv (x, 0) L -
    fieldTotalDerivative x (MvPolynomial.pderiv (x, 1) L)

noncomputable def fieldOscillatorLagrangian {ι : Type} [DecidableEq ι]
    (x : ι) : FieldJetPolynomial ι :=
  (1 / 2 : ℝ) • (fieldJetVar x 1 * fieldJetVar x 1) -
    (1 / 2 : ℝ) • (fieldJetVar x 0 * fieldJetVar x 0)

theorem fieldOscillator_euler_lagrange {ι : Type} [DecidableEq ι] (x : ι) :
    fieldEulerLagrangeResidual x (fieldOscillatorLagrangian x) =
      -(fieldJetVar x 0 + fieldJetVar x 2) := by
  simp [fieldEulerLagrangeResidual, fieldOscillatorLagrangian,
    fieldTotalDerivative, fieldJetVar]
  module

end LeanPhy.Classical
