import LeanPhy.FieldTheory.CCR
import Mathlib.Tactic.NoncommRing
import Mathlib.Tactic.Abel

/-!
# Majorana fermions and the Dirac-Majorana correspondence

A Majorana fermion is its own antiparticle, so it is a real linear combination of
a Dirac mode; this is the algebraic backbone of topological superconductors (the
Kitaev chain), of neutrino-mass model building, and of the parity of a Majorana
zero mode.  Everything here is pure ring algebra from the canonical
anticommutation relations of a single Dirac mode, with no Hilbert-space or
operator-domain input.

We take a Dirac mode with {c, c†} = 1 and c^2 = (c†)^2 = 0 and form the two real
combinations  g1 = c + c†  and  g2 = c - c†.  The physical Majorana operators
are gamma1 = g1 and gamma2 = -i g2; the factor -i is what flips the sign of
g2^2 and is recorded explicitly in `majorana2_sq` and `number_from_majorana`,
so the module never silently assumes a square root of -1 in the ring.

Proved here (no sorry, no axiom):

- g1 is an involution, g1^2 = 1;
- g2 satisfies g2^2 = -1, the algebraic image of the factor -i;
- the two anticommute, {g1, g2} = 0, so they define Clifford algebra Cl(1,1);
- the Dirac number operator is recovered:  g1 g2 = 2 c†c - 1, i.e.
  c†c = (1 - i gamma1 gamma2)/2 once the physical gamma2 = -i g2 is restored.
-/

namespace LeanPhy.Condensed

open LeanPhy.Quantum
open LeanPhy.FieldTheory

/-- A single Dirac mode, carried as its canonical anticommutation data.  This is
the same input as `FermionicMode`, restated so the Majorana constructions read
cleanly. -/
structure DiracMode where
  /-- Carrier ring of operators. -/
  A : Type
  [ringA : Ring A]
  /-- Annihilation operator. -/
  c : A
  /-- Creation operator. -/
  cdag : A
  /-- {c, c†} = 1. -/
  car : c * cdag + cdag * c = 1
  /-- c^2 = 0. -/
  c_sq : c * c = 0
  /-- (c†)^2 = 0. -/
  cdag_sq : cdag * cdag = 0

attribute [instance] DiracMode.ringA

namespace DiracMode

variable (M : DiracMode)

/-- The first real Majorana combination g1 = c + c†. -/
def majorana1 : M.A := M.c + M.cdag

/-- The second real Majorana combination g2 = c - c† (the physical Majorana is
-i g2; the factor -i is carried by the sign of the square, see `majorana2_sq`). -/
def majorana2 : M.A := M.c - M.cdag

/-- g1 is an involution: g1^2 = 1. -/
theorem majorana1_sq : M.majorana1 * M.majorana1 = 1 := by
  rw [majorana1, add_mul, mul_add, mul_add, M.c_sq, M.cdag_sq]
  simpa using M.car

/-- g2 squares to -1, the image of the factor -i turning (c - c†)^2 into -1. -/
theorem majorana2_sq : M.majorana2 * M.majorana2 = -1 := by
  have key : M.majorana2 * M.majorana2
      = -(M.c * M.cdag + M.cdag * M.c) + (M.c * M.c + M.cdag * M.cdag) := by
    rw [majorana2]; noncomm_ring
  rw [key, M.c_sq, M.cdag_sq, M.car]
  abel

/-- The two Majoranas anticommute: {g1, g2} = 0.  Together with the self-squares
this is the Clifford algebra Cl(1,1) generated by a single Dirac mode. -/
theorem majorana_anticommute : M.majorana1 * M.majorana2 + M.majorana2 * M.majorana1 = 0 := by
  have key : M.majorana1 * M.majorana2 + M.majorana2 * M.majorana1
      = 2 * (M.c * M.c) - 2 * (M.cdag * M.cdag) := by
    rw [majorana1, majorana2]; noncomm_ring
  rw [key, M.c_sq, M.cdag_sq]
  simp

/-- The parity operator P = g1 g2 anticommutes with g1:  g1 P + P g1 = 0.  This
is the algebraic form of the Z2 fermion parity grading. -/
theorem majorana1_anticommute_parity :
    M.majorana1 * (M.majorana1 * M.majorana2) + (M.majorana1 * M.majorana2) * M.majorana1 = 0 := by
  have hmg : M.majorana2 * M.majorana1 = -(M.majorana1 * M.majorana2) := by
    rw [eq_neg_iff_add_eq_zero, add_comm]; exact M.majorana_anticommute
  have hl : M.majorana1 * (M.majorana1 * M.majorana2) = M.majorana2 := by
    rw [← mul_assoc, M.majorana1_sq, one_mul]
  have hr : (M.majorana1 * M.majorana2) * M.majorana1 = -M.majorana2 := by
    rw [mul_assoc, hmg, mul_neg, hl]
  rw [hl, hr, add_neg_cancel]

/-- **Dirac-Majorana correspondence.**  The product of the two Majoranas is the
Dirac number operator:  g1 g2 = 2 c†c - 1.  Restoring the physical gamma2 = -i g2
this reads c†c = (1 - i gamma1 gamma2)/2, the standard Majorana form of the
occupation number. -/
theorem number_from_majorana : M.majorana1 * M.majorana2 = 2 * (M.cdag * M.c) - 1 := by
  have hcar' : M.c * M.cdag = 1 - M.cdag * M.c := by
    rw [eq_sub_iff_add_eq]; exact M.car
  have key : M.majorana1 * M.majorana2
      = -(M.c * M.cdag) + M.cdag * M.c := by
    rw [majorana1, majorana2]
    rw [show (M.c + M.cdag) * (M.c - M.cdag)
          = M.c * M.c - M.c * M.cdag + M.cdag * M.c - M.cdag * M.cdag from by noncomm_ring]
    rw [M.c_sq, M.cdag_sq, zero_sub, sub_zero]
  rw [key, hcar']
  noncomm_ring

end DiracMode

end LeanPhy.Condensed
