import LeanPhy.Quantum.Basic
import Mathlib.Tactic.NoncommRing

/-!
# Supersymmetry algebra

The minimal supersymmetry algebra in quantum mechanics is generated by a
nilpotent supercharge Q, its adjoint Q†, and the Hamiltonian H = {Q, Q†}.
Everything here is pure ring algebra with those relations as explicit
hypotheses, so the module is checked without any Hilbert-space or
operator-domain input.

Proved here (no sorry, no axiom):

- H is the anticommutator {Q, Q†};
- Q and Q† are nilpotent, Q^2 = 0 and (Q†)^2 = 0;
- the Hamiltonian automatically commutes with the supercharge, [H, Q] = 0 and
  [H, Q†] = 0, the statement that supersymmetry is a symmetry of the spectrum;
- a state annihilated by both Q and Q† has zero energy, H v = 0, the algebraic
  shadow of the BPS / supersymmetric-ground-state condition;
- a concrete 2x2 realization with Q = [[0,1],[0,0]] and H = 1.
-/

namespace LeanPhy.HighEnergy

open LeanPhy.Quantum

/-- The data of a minimal supersymmetric quantum mechanics: a supercharge, its
adjoint, and the Hamiltonian they determine. -/
structure SusyQM where
  /-- Carrier ring of operators. -/
  A : Type
  [ringA : Ring A]
  /-- The supercharge Q. -/
  Q : A
  /-- The adjoint supercharge Q†. -/
  Qdag : A
  /-- The supercharge is nilpotent. -/
  Q_sq : Q * Q = 0
  /-- The adjoint supercharge is nilpotent. -/
  Qdag_sq : Qdag * Qdag = 0

attribute [instance] SusyQM.ringA

namespace SusyQM

variable (S : SusyQM)

/-- The Hamiltonian of a supersymmetric quantum mechanics, H = {Q, Q†}. -/
def H : S.A := S.Q * S.Qdag + S.Qdag * S.Q

/-- The Hamiltonian is the anticommutator of the supercharge and its adjoint. -/
theorem H_eq_anticommutator : S.H = anticommutator S.Q S.Qdag := rfl

/-- The supercharge is nilpotent: Q^2 = 0. -/
theorem Q_nilpotent : S.Q * S.Q = 0 := S.Q_sq

/-- The adjoint supercharge is nilpotent: (Q†)^2 = 0. -/
theorem Qdag_nilpotent : S.Qdag * S.Qdag = 0 := S.Qdag_sq

/-- The Hamiltonian commutes with the supercharge, [H, Q] = 0.  The commutator
reduces to Q†(Q Q) - (Q Q)Q†, which vanishes by nilpotency. -/
theorem H_commutator_Q : ⟦S.H, S.Q⟧ = 0 := by
  rw [H, commutator]
  have key : (S.Q * S.Qdag + S.Qdag * S.Q) * S.Q - S.Q * (S.Q * S.Qdag + S.Qdag * S.Q)
      = S.Qdag * (S.Q * S.Q) - (S.Q * S.Q) * S.Qdag := by noncomm_ring
  rw [key, S.Q_sq, mul_zero, zero_mul, sub_zero]

/-- The Hamiltonian commutes with the adjoint supercharge, [H, Q†] = 0.  The
commutator reduces to Q(Q† Q†) - (Q† Q†)Q, which vanishes by nilpotency. -/
theorem H_commutator_Qdag : ⟦S.H, S.Qdag⟧ = 0 := by
  rw [H, commutator]
  have key : (S.Q * S.Qdag + S.Qdag * S.Q) * S.Qdag - S.Qdag * (S.Q * S.Qdag + S.Qdag * S.Q)
      = S.Q * (S.Qdag * S.Qdag) - (S.Qdag * S.Qdag) * S.Q := by noncomm_ring
  rw [key, S.Qdag_sq, mul_zero, zero_mul, sub_zero]

/-- A state annihilated by both supercharges has zero energy: if Q v = 0 and
Q† v = 0 then H v = 0.  This is the algebraic form of the BPS condition. -/
theorem H_apply_eq_zero {v : S.A} (hQ : S.Q * v = 0) (hQd : S.Qdag * v = 0) :
    S.H * v = 0 := by
  rw [H]
  have key : (S.Q * S.Qdag + S.Qdag * S.Q) * v = S.Q * (S.Qdag * v) + S.Qdag * (S.Q * v) := by
    noncomm_ring
  rw [key, hQd, hQ]
  simp

end SusyQM

/-! ## A concrete realization -/

namespace SusyExample

/-- The simplest 2x2 nilpotent supercharge, Q = [[0,1],[0,0]]. -/
def susyQ : Operator 2 := !![0, 1; 0, 0]

/-- The adjoint, Q† = [[0,0],[1,0]]. -/
def susyQdag : Operator 2 := !![0, 0; 1, 0]

/-- The 2x2 supersymmetric quantum mechanics instance. -/
def susyExample : SusyQM where
  A := Operator 2
  Q := susyQ
  Qdag := susyQdag
  Q_sq := by
    ext i j; fin_cases i <;> fin_cases j <;>
      simp [susyQ, Matrix.mul_apply, Fin.sum_univ_two]
  Qdag_sq := by
    ext i j; fin_cases i <;> fin_cases j <;>
      simp [susyQdag, Matrix.mul_apply, Fin.sum_univ_two]

/-- For this realization the Hamiltonian is the identity, H = 1, so the whole
spectrum is supersymmetric. -/
theorem susyExample_H : SusyQM.H susyExample = 1 := by
  show susyQ * susyQdag + susyQdag * susyQ = 1
  ext i j; fin_cases i <;> fin_cases j <;>
    simp [susyQ, susyQdag, Matrix.add_apply]

end SusyExample

end LeanPhy.HighEnergy
